server:
  port: 8080
spring:
  application:
    name: "PruebaBackendVortex"
  devtools:
    add-properties: true
  datasource:
    url: "jdbc:mysql://localhost:3306/vortex"
    username: "root"
    password: ""
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
